name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build --stacktrace
      - name: upload fabric artifacts
        uses: actions/upload-artifact@v3
        with:
          name: fabric
          path: fabric/build/libs/*-fabric.jar
      - name: upload forge artifacts
        uses: actions/upload-artifact@v3
        with:
          name: forge
          path: forge/build/libs/*-forge.jar
